In [2]:
conda install pillow

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [57]:
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.image as img
from PIL import Image as im
images = np.zeros([20,300,300,3])
rootDir = 'photos'
list1 = []
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
for fname in fileList:
    print('\t%s' % fname)
    list1.append(fname)
list1.pop()

Found directory: photos
	1.jpg
	10.jpg
	11.jpg
	12.jpg
	13.jpg
	14.jpg
	15.jpg
	16.jpg
	17.jpg
	18.jpg
	19.jpg
	2.jpg
	20.jpg
	3.jpg
	4.jpg
	5.jpg
	6.jpg
	7.jpg
	8.jpg
	9.jpg
	Multi images array.ipynb


'Multi images array.ipynb'

In [58]:
img1 = im.open('photos/1.jpg')
print(img1)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=275x183 at 0x135B015B5F8>


In [69]:
list5 = []
for i in list1:
    img1 = im.open(i)
    img1 = img1.resize((200,200))
    list5.append(np.array(img1))
print(list5[4])
arr = np.array(list5)
print(arr.dtype,arr.shape)

[[[252 252 252]
  [252 252 252]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [252 252 252]]

 [[252 252 252]
  [252 252 252]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [252 252 252]]

 [[252 252 252]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[253 253 253]
  [253 253 253]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [253 253 253]]]
uint8 (20, 200, 200, 3)
